[markata]
# bump site version to bust GitHub actions cache
site_version = 2
glob_patterns = "pages/**/*.md"
output_dir = "static"
assets_dir = "static"
hooks = ["plugins.load_json", "markata.plugins.covers", "markata.plugins.base_cli",]
# hooks = ["markata.plugins.publish_source", "plugins.index", "default", ]
# disabled_hooks = ["default"]
url = "https://images.pype.dev"
title = "Images for pype.dev"
description = "Images for pype.dev"
rss_description = "Images for pype.dev"
author_name = "Pypeaday"
author_email = "nic.payne@protonmail.com"
icon = "bitmoji.png"
lang = "en"
# post_template = "pages/templates/post_template.html"
theme_color = "#322D39"
background_color = "#B73CF6"
start_url = "/"
site_name = "Pypeaday"
short_name = "pype"
display = "minimal-ui"
twitter_card = "summary_large_image"
twitter_creator = "@pypeaday"
twitter_site = "@pypeaday"

[markata.glob_json]
url='https://pype.dev/markata.json'

[markata.archive.pages.archive]

[markata.archive.pages.python]
tags='python'

[markata.archive.pages.linux]
tags='linux'

[markata.archive.pages.vim]
tags='vim'

[markata.archive.pages.kedro]
tags='kedro'

[[markata.covers]]
name='-dev'
template = "static/cover-template.png"
# font = "static/waterlilly-script.ttf"
font = "./static/JosefinSans-Regular.ttf"
text_font = "./static/JosefinSans-Regular.ttf"
font_color = "rgb(185,155,165)"
text_font_color = "rgb(255,255,255)"
text_key = 'description'
padding = [0, 40, 100, 300]
text_padding = [0,0]

[[markata.covers]]
name=''
template = "static/og-template.png"
# font = "static/waterlilly-script.ttf"
font = "./static/JosefinSans-Regular.ttf"
font_color = "rgb(255,255,255)"
# text_key = 'description'
text_font = "./static/JosefinSans-Regular.ttf"
text_font_color = "rgb(200,200,200)"
text_key = 'description'
padding = [10, 10, 100, 300]
text_padding = [0,0]

[[markata.covers]]
name='-og'
template = "static/og-template.png"
# font = "static/waterlilly-script.ttf"
font = "./static/JosefinSans-Regular.ttf"
font_color = "rgb(255,255,255)"
# text_key = 'description'
text_font = "./static/JosefinSans-Regular.ttf"
text_font_color = "rgb(200,200,200)"
text_key = 'description'
padding = [10, 10, 100, 300]
text_padding = [0,0]

[[markata.covers]]
name='-hashnode'
template = "static/hashnode-template.png"
# font = "static/waterlilly-script.ttf"
font = "./static/JosefinSans-Regular.ttf"
font_color = "rgb(255,255,255)"
text_font = "./static/JosefinSans-Regular.ttf"
text_font_color = "rgb(200,200,200)"
text_key = 'description'
padding = [0, 40, 100, 300]
text_padding = [0,0]

[[markata.seo]]
name = "og:type"
property = "og:type"
content = "article"

[[markata.seo]]
name = "og:author"
property = "og:author"
content = "Pypeaday"

[[markata.seo]]
name = "og:site_name"
property = "og:site_name"
content = "Pypeaday"

[[markata.seo]]
name = "theme-color"
content="#322D39"


