name: 📷 Deploy images

on:
  workflow_dispatch:
  schedule:
    # 0 central time
    - cron: '0 5 * * *' 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install markata
        run: pip install git+https://github.com/WaylonWalker/markata.git@develop python-twitter background # checksumdir

      - run: markata --version
      - run: markata --help

      - name: run markata
        run: markata build --no-pretty

      - name: install cwebp
        run: |
           curl -s https://raw.githubusercontent.com/Intervox/node-webp/latest/bin/install_webp | sudo bash
           pip install webp-converter

      - name: convert to webp
        run: webpc -q=50 -o ./static
      
      - name: ImageMagick Action
        uses: jruipinto/ImageMagick-action@v1
        with:
          command: mogrify -path static/thumb -auto-orient -resize 300x300 static/*.jpg

      - name: ImageMagick Action
        uses: jruipinto/ImageMagick-action@v1
        with:
          command: mogrify -path static/thumb -auto-orient -resize 300x300 static/*.png

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GH_PAT }}
          compressOnly: true
          
      - name: make index
        run: python template/render.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto thumbnail and compress
